---
tailscaleSupportedOperations:
  - diagnose
  - down
  - install
  - status
  - uninstall
  - up
  - update

tailscaleSupportMatrix:
  Darwin:
    - x86_64
    - aarch64
  Debian:
    - x86_64
    - aarch64
    - armv7l
