---
- name: Find the host SSH key in 1Password
  ansible.builtin.include_tasks: find_key.yml

- name: Require an existing host SSH key item
  ansible.builtin.assert:
    that:
      - provisionHostSshMatchingItems | length == 1
    fail_msg: >-
      SSH Key item {{ provisionHostSshItemName }} does not exist in vault
      {{ onePasswordVault }}. Run the ensure_key operation first.
