---
- name: Install VS Code via Homebrew
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts.os_family == 'Darwin'

- name: Install VS Code via apt
  ansible.builtin.include_tasks: Debian.yml
  when: ansible_facts.os_family == 'Debian'

- name: Validate the VS Code install
  ansible.builtin.include_tasks: validate.yml

- name: Sync VS Code extensions
  ansible.builtin.include_tasks: extensions.yml
  when: vscodeExtensions | length > 0
