---
onePasswordVault: Personal-Automation
onePasswordTokenFile: >-
  {{ lookup('ansible.builtin.env', 'HOME') }}/.config/op/op-service-account-token
onePasswordSambaQueries:
  sambaUsername: >-
    op://{{ onePasswordVault }}/{{ sambaPasswordOpItem }}/username
  sambaEffectivePassword: >-
    op://{{ onePasswordVault }}/{{ sambaPasswordOpItem }}/password
