---
- name: "Resolve SSH route | {{ inventory_hostname ~ ' -> ' ~ resolvedSshHost }}"
  ansible.builtin.set_fact:
    sshResolvedHost: "{{ resolvedSshHost }}"
    ansible_host: "{{ resolvedSshHost }}"
    ansible_ssh_common_args: >-
      -F /dev/null
      -o UserKnownHostsFile=/dev/null
      -o GlobalKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
  vars:
    resolvedSshHost: >-
      {{
        vpnHostname ~ '.' ~ vpnDomain
        if useVpn | bool
        else inventory_hostname
        if ',' in inventory_file
        else hostName ~ '.local'
      }}
