---
- name: Stop and disable the Tailscale service
  ansible.builtin.service:
    name: tailscaled
    enabled: false
    state: stopped
  become: true
  failed_when: false

- name: Ensure the Tailscale package is absent
  ansible.builtin.apt:
    name: tailscale
    state: absent
    purge: true
  become: true
