---
- name: Ensure Tailscale is installed before updating
  ansible.builtin.include_tasks: install.yml

- name: Update Tailscale on macOS
  ansible.builtin.include_tasks: update-Darwin.yml
  when: ansible_facts.os_family == 'Darwin'

- name: Update Tailscale on Debian-family Linux
  ansible.builtin.include_tasks: update-Debian.yml
  when:
    - ansible_facts.os_family == 'Debian'
    - not ansible_check_mode
