---
onePasswordVault: Personal-Automation
onePasswordTokenFile: >-
  {{ lookup('ansible.builtin.env', 'HOME') }}/.config/op/op-service-account-token
sshKeyPrefix: sshkey
sshLoginPrefix: user
onePasswordSshUserPassQueries:
  ansible_user: >-
    op://{{ onePasswordVault }}/{{ sshLoginPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/username
  ansible_password: >-
    op://{{ onePasswordVault }}/{{ sshLoginPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/password
  ansible_private_key: >-
    op://{{ onePasswordVault }}/{{ sshKeyPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/private key?ssh-format=openssh
