---
onePasswordTasks:
  - ssh_user_pass

onePasswordChoices:
  - ssh_user_pass
  - samba
  - tailscale

op_queries: {}

onePasswordVault: Personal-Automation
sshKeyPrefix: sshkey
sshLoginPrefix: user

onePasswordTailscaleAPIKey: AuthKey, Tailscale Auth Key - Ansible Provisioning
onePasswordTokenPath: .config/op/op-service-account-token
onePasswordTokenFile: "{{ superAgentHomeDir }}/{{ onePasswordTokenPath }}"

op_token_file: "{{ onePasswordTokenFile }}"

onePasswordSshUserPassQueries:
  ansible_user: >-
    op://{{ onePasswordVault }}/{{ sshLoginPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/username
  ansible_password: >-
    op://{{ onePasswordVault }}/{{ sshLoginPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/password
  ansible_private_key: >-
    op://{{ onePasswordVault }}/{{ sshKeyPrefix }}-{{
    (hostName | default(inventory_hostname)).split('.')[0]
    }}/private key?ssh-format=openssh

onePasswordSambaQueries:
  sambaUsername: >-
    op://{{ onePasswordVault }}/{{ sambaPasswordOpItem }}/username
  sambaEffectivePassword: >-
    op://{{ onePasswordVault }}/{{ sambaPasswordOpItem }}/password

onePasswordTailscaleQueries:
  tailscaleAuthKey: >-
    op://{{ onePasswordVault }}/{{ onePasswordTailscaleAPIKey }}/credential
