---
- name: Install Claude Code
  hosts: all
  gather_facts: false
  roles:
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: claude
      claudeOperation: install
