---
- name: Install LM Studio
  hosts: all
  gather_facts: false
  roles:
    - role: set_facts
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: lm_studio
      lmStudioOperation: install
