---
- name: Ping hosts
  hosts: all
  gather_facts: false
  become: false
  serial: "20%"

  roles:
    - 1password_ssh_user_pass
    - ssh

  tasks:
    - name: Ping
      ansible.builtin.ping:
      tags: [ping]
