---
- name: Ping hosts
  hosts: all
  gather_facts: false
  become: false
  serial: "20%"

  roles:
    - role: set_facts
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - ssh

  tasks:
    - name: Ping
      ansible.builtin.ping:
      tags: [ping]
      timeout: 10
