---
- name: Install the host SSH public key
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: ssh
      sshOperation: prepare_password_connection
    - role: provision_host
      provisionHostSshOperation: install_key
