---
- name: Ensure the host SSH key exists in 1Password
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: provision_host
      provisionHostSshOperation: ensure_key
