---
- name: Validate key access and disable SSH password authentication
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: ssh
      sshOperation: prepare_key_connection
    - role: provision_host
      provisionHostSshOperation: disable_password
