---
- name: Provision host SSH key access and disable password authentication
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: provision_host
      provisionHostSshOperation: provision
