---
- name: Install the host SSH public key
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: provision_host
      provisionHostSshOperation: install_key
