---
- name: Install Samba
  hosts: all
  gather_facts: false
  roles:
    - role: set_facts
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
        - samba
    - role: ssh
    - role: samba
      sambaOperation: install
