---
- name: Run Tailscale operations
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: set_facts
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
        - tailscale
    - role: ssh
    - role: tailscale
