---
- name: Install Tailscale
  hosts: all
  gather_facts: false
  roles:
    - role: onepassword
      onePasswordTasks:
        - ssh_user_pass
    - role: ssh
    - role: tailscale
      tailscaleOperation: install
